#!/usr/bin/env bash

if [[ $1 = "-h" || $1 = "--help" ]]
then
    echo "Determines which filesystem is the device in"
    exit 0
fi

function append_line()
{
    cat
    echo
}

lsblk -o NAME,LABEL -l | tail -n+2 | append_line | \
while read -r -a line
do
    if [[ -z $device || -z `grep "^$device" <<<${line[0]}` ]]
    then
        echo "$device $name"
        device=${line[0]}
        name="${line[1]}"
    fi
    if [[ ${line[1]} ]]
    then
        name="${line[1]}"
    fi
done | tail -n+2
