#!/usr/bin/env bash

function append_line()
{
    cat
    $1
}

NEW_STAT=`sed "s/\s\+/ /g" /proc/diskstats | sed "s/^ //" | cut -f 3,6,10 -d " "`
NEW_TIME=`date "+%s.%N"`

echo $DISK_STAT | append_line "echo $NEW_STAT" | python -c "
from __future__ import print_function
import sys

def read_stat():
    line = sys.stdin.readline().strip().split()
    return {line[i]: (int(line[i+1]), int(line[i+2])) for i in range(0, len(line), 3)}

prev = read_stat()
next = read_stat()

diff = float($NEW_TIME)-float($DISK_TIME)
unit=1024.0

for device in sorted(next):
    print(device, end=' ')
    if device in prev:
        for i in range(len(next[device])):
            print(unit*(next[device][i]-prev[device][i]) / diff, end=' ')
    else:
        for i in range(len(next[device])):
            print(unit*(next[device][i]) / diff, end=' ')
    print('')
"

DISK_TIME=$NEW_TIME
DISK_STAT=$NEW_STAT
