#!/usr/bin/python3
from html import escape as htmlescape
import sys
import argparse

def main(args):
    print("<table", *args.extra, ">")
    def formatline(line, head=False, extra=""):
        if head:
            sep1='<th>'
            sep2='</th>'
        else:
            sep1='<td>'
            sep2='</td>'
        print("<tr " + extra + ">" + sep1 + (sep2+sep1).join(map(htmlescape, line.strip().split(None, args.columns))) + sep2 + "</tr>")
    if args.head:
        formatline(sys.stdin.readline(), True)
    for i, line in enumerate(sys.stdin):
        formatline(line, False, 'style="background-color: lightgrey;"' if i%2==0 else "")

    print("</table>")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Format stdin into HTML table',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
        )
    parser.add_argument('-head', '--head', dest="head", action="store_true", default=False)
    parser.add_argument('-c', '--columns', dest="columns", type=int, default=3)
    parser.add_argument("extra", type=str, nargs="*", default=[])
    
    exit(main(parser.parse_args()))
