#!/usr/bin/env bash

if [ "$1" = '-c' ]
then
    SHELL_COMMAND="$SHELL -c"
    shift
fi

filename=`date +%Y_%m_%d.%Hh%Mm%S.%4Ns_UTC%z`.log
echo [from] `hostname`:`pwd` > $filename
echo [running] "$@" >> $filename
echo [output] >> $filename
if [ -z "$SHELL_COMMAND" ]
then
    "$@"
else
    $SHELL_COMMAND "$*" 
fi > >(tee -a $filename) 2> >(tee -a $filename 1>&2)