#!/usr/bin/env bash

df -h --output=source,used,size,pcent | grep -v "\s0%$" | column -t
echo

#device-name table
devices=(`device_fs | sed "s/\(^[^ ]\+\) $/\1 -/"`)

function find_name()
{
    for i in `seq 0 2 $((${#devices[*]}-1))`
    do
        if [ ${devices[$i]} = $1 ]
        then
            echo ${devices[$((i+1))]}
            return 0
        fi
    done
    return 1
}

function prepend()
{
    echo $1
    cat
}

source disk_stat | \
while read -r -a line
do
    if find_name ${line[0]} &> /dev/null
    then 
        state=`sudo -n hdparm -C /dev/${line[0]} 2> /dev/null | tail -n1 | cut -f2 -d":" | column`
        printf "%s %f %f %s $state\n" ${line[*]} `find_name ${line[0]}`
    fi
done | prepend "device read write" | hr -gi |  column -t
